version: '3'
services:
  pgnet:
    image: unplgtc/pgnet:release
    build:
      context: .
      dockerfile: ./docker/Dockerfile-Prod
      args:
        - NEXT_PUBLIC_ENV=prod
    ports:
      - 3000
