---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: pgnet-staging
  namespace: staging
spec:
  prefix: /
  host: staging.paulguyot.net
  rewrite: /
  service: pgnet-staging:80
---
apiVersion: v1
kind: Service
metadata:
  name: pgnet-staging
  namespace: staging
spec:
  ports:
  - name: pgnet-stg
    port: 80
    targetPort: 3000
  selector:
    app: pgnet-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgnet-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgnet-staging
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pgnet-staging
        version: 1.0.0
    spec:
      containers:
      - name: pgnet-staging
        image: unplgtc/pgnet:staging
        imagePullPolicy: Always
        ports:
        - name: pgnet-stg
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /readycheck
            port: 3000
          initialDelaySeconds: 3
      imagePullSecrets:
      - name: regcred
